name: FrameStore
main: me.maciekmm.FrameStore.FrameStore
version: B0.9
author: maciekmm
depend: [Vault]
commands:
   fs:
      description: FrameStore global command
      usage: /<command>

