name: FrameStore
main: me.maciekmm.FrameStore.FrameStore
version: PR1.4.0
author: maciekmm
depend: [Vault]
commands:
   fs:
      description: FrameStore global command
      usage: /<command>

